language: node_js

env:
  - DATABASE_URL = 'postgresql://postgres@localhost:5432/registration_tests';

node_js:  
  - "8.9.4"

before_script:
  - psql -c 'create database  registration_tests;' -U postgres
  - psql -U postgres -d registration_tests -a -f table.sql

  
addons:
    apt:
    packages:
    - postgresql-server-dev-9.2